name: CI

on:
  push:
    branches:
      - newPushGIT

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install -DskipTests

    - name: Run Selenium Tests
      run: mvn test
